<?php
header('Content-Type: application/json');

require_once __DIR__ . '/db.php';
require_once __DIR__ . '/analyze.php';

$symbol = $_GET['symbol'] ?? '';
$timeframe = $_GET['timeframe'] ?? '1M';

if (!$symbol) {
    http_response_code(400);
    echo json_encode(['error' => 'No symbol provided']);
    exit;
}

try {
    $mysqli = db_connect();
    $base = analyze_symbol($mysqli, $symbol, 'day');

    if (isset($base['error'])) {
        http_response_code(400);
        echo json_encode($base);
        exit;
    }

    $latest = isset($base['latest']['close']) ? (float)$base['latest']['close'] : 0.0;
    $prevClose = isset($base['prev_close']) ? (float)$base['prev_close'] : 0.0;
    $chgPct = ($prevClose > 0) ? (($latest - $prevClose) / $prevClose) * 100 : 0.0;

    $latestIdx = isset($base['prices']) ? count($base['prices']) - 1 : -1;
    $rsi = ($latestIdx >= 0 && isset($base['rsi'][$latestIdx]) && $base['rsi'][$latestIdx] !== null) ? (float)$base['rsi'][$latestIdx] : null;
    $macdHist = ($latestIdx >= 0 && isset($base['macd']['hist'][$latestIdx])) ? (float)$base['macd']['hist'][$latestIdx] : null;

    $recommendation = map_recommendation($base['signal'] ?? 'HOLD', $base['global_sentiment'] ?? 'NEUTRAL', $rsi, $macdHist);
    $confidence = estimate_confidence($base['signal'] ?? 'HOLD', $base['global_sentiment'] ?? 'NEUTRAL', $rsi, $macdHist, $chgPct);

    $entry = $base['trading_plan']['entry'] ?? null;
    $tp = $base['trading_plan']['take_profit'] ?? null;
    $sl = $base['trading_plan']['cut_loss'] ?? null;

    $analysis = [
        'technical_analysis' => build_technical_text($base, $latest, $chgPct, $rsi, $macdHist),
        'fundamental_analysis' => build_fundamental_text($base),
        'sentiment_analysis' => build_sentiment_text($base, $chgPct),
        'risk_factors' => build_risk_text($base, $rsi, $chgPct),
        'conclusion' => build_conclusion_text($recommendation, $confidence, $entry, $tp, $sl),
        'recommendation' => $recommendation,
        'recommendation_strength' => map_strength($recommendation),
        'confidence_level' => $confidence,
        'entry_price' => $entry,
        'take_profit' => $tp,
        'stop_loss' => $sl,
        'raw_text' => 'Generated by local free engine'
    ];

    echo json_encode([
        'success' => true,
        'symbol' => $symbol,
        'timeframe' => $timeframe,
        'timestamp' => date('Y-m-d H:i:s'),
        'engine' => 'FREE_LOCAL',
        'analysis' => $analysis,
        'data_context' => [
            'latest_price' => $latest,
            'change_pct' => round($chgPct, 2),
            'trend' => $base['signal'] ?? 'HOLD',
            'rsi' => $rsi,
            'macd_signal' => $macdHist,
            'global_sentiment' => $base['global_sentiment'] ?? 'NEUTRAL',
            'fund_status' => $base['fund_status'] ?? 'N/A'
        ]
    ]);
} catch (Exception $e) {
    http_response_code(500);
    echo json_encode(['error' => 'Free analysis failed: ' . $e->getMessage()]);
}

function map_recommendation($signal, $sentiment, $rsi, $macdHist) {
    $sig = strtoupper((string)$signal);
    $sent = strtoupper((string)$sentiment);

    if ($sig === 'STRONG BUY' && $sent === 'BULLISH' && ($rsi === null || $rsi < 75) && ($macdHist === null || $macdHist > 0)) {
        return 'HOT';
    }
    if ($sig === 'STRONG SELL' || $sig === 'SELL') {
        return 'SELL';
    }
    if ($sig === 'STRONG BUY' || $sig === 'BUY') {
        return 'BUY';
    }
    return 'HOLD';
}

function map_strength($recommendation) {
    $map = [
        'SELL' => 'sangat negatif',
        'HOLD' => 'netral',
        'BUY' => 'positif',
        'HOT' => 'sangat positif'
    ];
    return $map[$recommendation] ?? 'netral';
}

function estimate_confidence($signal, $sentiment, $rsi, $macdHist, $chgPct) {
    $score = 0;
    $sig = strtoupper((string)$signal);
    $sent = strtoupper((string)$sentiment);

    if ($sig === 'STRONG BUY' || $sig === 'STRONG SELL') $score += 2;
    if ($sig === 'BUY' || $sig === 'SELL') $score += 1;
    if ($sent === 'BULLISH' || $sent === 'BEARISH') $score += 1;
    if ($rsi !== null && $rsi >= 35 && $rsi <= 65) $score += 1;
    if ($macdHist !== null && abs($macdHist) > 0.2) $score += 1;
    if (abs($chgPct) >= 1.0) $score += 1;

    if ($score >= 6) return 'sangat tinggi';
    if ($score >= 4) return 'tinggi';
    if ($score >= 2) return 'sedang';
    return 'rendah';
}

function build_technical_text($base, $latest, $chgPct, $rsi, $macdHist) {
    $signal = strtoupper((string)($base['signal'] ?? 'HOLD'));
    $details = (string)($base['signal_details'] ?? '-');
    $rsiText = $rsi === null ? '-' : number_format($rsi, 2);
    $macdText = $macdHist === null ? '-' : number_format($macdHist, 3);

    return "Harga terakhir berada di " . number_format($latest, 0, ',', '.') . " dengan perubahan harian " . number_format($chgPct, 2) . "%. " .
           "Sinyal teknikal saat ini " . $signal . " dengan konfirmasi: " . $details . ". " .
           "RSI di level " . $rsiText . " dan MACD histogram " . $macdText . ". " .
           "Secara teknikal, fokus pada validasi momentum dan disiplin di area stop loss yang telah dihitung.";
}

function build_fundamental_text($base) {
    $fundStatus = $base['fund_status'] ?? 'N/A';
    $fundScore = isset($base['fund_score']) && $base['fund_score'] !== null ? number_format((float)$base['fund_score'], 2) : 'N/A';
    $f = $base['fundamental'] ?? null;

    if (!$f) {
        return "Data fundamental historis belum lengkap. Skor fundamental saat ini: " . $fundScore . " (" . $fundStatus . "). " .
               "Disarankan validasi tambahan PER, PBV, dan ROE terbaru sebelum pengambilan posisi besar.";
    }

    $pe = isset($f['pe']) ? $f['pe'] : null;
    $pbv = isset($f['pbv']) ? $f['pbv'] : null;
    $roe = isset($f['roe']) ? $f['roe'] : null;

    return "Skor fundamental " . $fundScore . " dengan status " . $fundStatus . ". " .
           "Parameter utama: PER=" . ($pe !== null ? number_format((float)$pe, 2) : '-') . ", " .
           "PBV=" . ($pbv !== null ? number_format((float)$pbv, 2) : '-') . ", " .
           "ROE=" . ($roe !== null ? number_format((float)$roe, 2) . '%' : '-') . ". " .
           "Gunakan fundamental sebagai filter kualitas, sementara timing tetap mengacu ke teknikal.";
}

function build_sentiment_text($base, $chgPct) {
    $g = strtoupper((string)($base['global_sentiment'] ?? 'NEUTRAL'));
    $gd = (string)($base['global_sentiment_details'] ?? 'No major catalysts');

    return "Sentimen pasar terdeteksi " . $g . ". Rangkuman sentimen: " . $gd . ". " .
           "Perubahan harga harian " . number_format($chgPct, 2) . "% menunjukkan respons pasar saat ini. " .
           "Konsistensi sentimen dengan trend teknikal akan meningkatkan probabilitas keberhasilan entry.";
}

function build_risk_text($base, $rsi, $chgPct) {
    $risk = [];
    if ($rsi !== null && $rsi > 70) $risk[] = 'RSI overbought, rawan koreksi jangka pendek';
    if ($rsi !== null && $rsi < 30) $risk[] = 'RSI oversold, volatilitas rebound tinggi';
    if (abs($chgPct) > 3) $risk[] = 'Pergerakan harian tinggi, potensi whipsaw meningkat';
    if (strtoupper((string)($base['global_sentiment'] ?? 'NEUTRAL')) === 'BEARISH') $risk[] = 'Sentimen global bearish menekan peluang bullish';
    if (empty($risk)) $risk[] = 'Risiko utama berada pada disiplin eksekusi dan money management';

    return implode('. ', $risk) . '.';
}

function build_conclusion_text($recommendation, $confidence, $entry, $tp, $sl) {
    return "Rekomendasi akhir: " . $recommendation . " dengan keyakinan " . $confidence . ". " .
           "Rencana trading: entry di " . ($entry !== null ? number_format((float)$entry, 0, ',', '.') : '-') .
           ", take profit di " . ($tp !== null ? number_format((float)$tp, 0, ',', '.') : '-') .
           ", dan stop loss di " . ($sl !== null ? number_format((float)$sl, 0, ',', '.') : '-') . ". " .
           "Gunakan sizing bertahap dan evaluasi ulang jika struktur tren berubah.";
}
