<?php
require_once __DIR__ . '/db.php';
$mysqli = db_connect();

$stocks = [
  'AALI' => 'Adaro Minerals',
  'ABBA' => 'Mahaka Media Tbk.',
  'ABDA' => 'Mahaka Radio Integra',
  'ACES' => 'Astra International Tbk.',
  'ADHI' => 'Adaro Energy Tbk.',
  'ADRO' => 'Adaro Energy Tbk.',
  'AKRA' => 'AKR Corporindo Tbk.',
  'AMRT' => 'Ace Hardware Indonesia Tbk.',
  'AMMN' => 'Amman Mineral Internasional',
  'ANTM' => 'Aneka Tambang Tbk.',
  'ARTO' => 'Amman Mineral Internasional',
  'ASII' => 'Astra International Tbk.',
  'ASRI' => 'Asuransi Ramayana Tbk.',
  'BABP' => 'Bank Neo Commerce Tbk.',
  'BACA' => 'Bank Capital Indonesia Tbk.',
  'BANK' => 'Bank Aladin Syariah Tbk.',
  'BBCA' => 'Bank Central Asia Tbk.',
  'BBNI' => 'Bank Negara Indonesia (Persero) Tbk.',
  'BBRI' => 'Bank Rakyat Indonesia (Persero) Tbk.',
  'BBTN' => 'Bank Tabungan Negara (Persero) Tbk.',
  'BDMN' => 'Bank Danamon Indonesia Tbk.',
  'BFIN' => 'BFI Finance Indonesia Tbk.',
  'BGTG' => 'Bank Ganesha Tbk.',
  'BINA' => 'Bank Ina Perdana Tbk.',
  'BJBR' => 'Bank Pembangunan Daerah Jawa Barat dan Banten Tbk.',
  'BJTM' => 'Bank Pembangunan Daerah Jawa Timur Tbk.',
  'BMRI' => 'Bank Mandiri (Persero) Tbk.',
  'BMTR' => 'Global Mediacom Tbk.',
  'BNBA' => 'Bank Bumi Arta Tbk.',
  'BNGA' => 'Bank CIMB Niaga Tbk.',
  'BNII' => 'Bank Maybank Indonesia Tbk.',
  'BNLI' => 'Bank Maybank Indonesia Tbk.',
  'BRIS' => 'Bank Syariah Indonesia Tbk.',
  'BSDE' => 'Bumi Serpong Damai Tbk.',
  'BTPS' => 'Bank BTPN Syariah Tbk.',
  'BVIC' => 'Bank Victoria International Tbk.',
  'BWPT' => 'Eagle High Plantations Tbk.',
  'BYAN' => 'Bayan Resources Tbk.',
  'CARS' => 'Bank Neo Commerce Tbk.',
  'CASS' => 'Cardig Aero Services Tbk.',
  'CEKA' => 'Wilmar Cahaya Indonesia Tbk.',
  'CPIN' => 'Indofood CBP Sukses Makmur Tbk.',
  'CTRA' => 'Ciputra Development Tbk.',
  'DILD' => 'Intiland Development Tbk.',
  'DOID' => 'Delta Dunia Makmur Tbk.',
  'DSNG' => 'Delta Dunia Makmur Tbk.',
  'ELTY' => 'Intiland Development Tbk.',
  'EMTK' => 'Elang Mahkota Teknologi Tbk.',
  'ENRG' => 'Energi Mega Persada Tbk.',
  'ERAA' => 'Erajaya Swasembada Tbk.',
  'EXCL' => 'XL Axiata Tbk.',
  'FREN' => 'Smartfren Telecom Tbk.',
  'GGRM' => 'Gudang Garam Tbk.',
  'GOTO' => 'GoTo Gojek Tokopedia Tbk.',
  'HEAL' => 'Medikaloka Hermina Tbk.',
  'HMSP' => 'Hanjaya Mandala Sampoerna Tbk.',
  'HRUM' => 'Harum Energy Tbk.',
  'ICBP' => 'Indofood CBP Sukses Makmur Tbk.',
  'INCO' => 'Aneka Tambang Tbk.',
  'INDF' => 'Indofood Sukses Makmur Tbk.',
  'INDY' => 'Indika Energy Tbk.',
  'INKP' => 'Indah Kiat Pulp & Paper Tbk.',
  'INTP' => 'Indofood Sukses Makmur Tbk.',
  'ISAT' => 'Indosat Tbk.',
  'ITMG' => 'Indo Tambangraya Megah Tbk.',
  'JPFA' => 'Japfa Comfeed Indonesia Tbk.',
  'JSMR' => 'Bumi Serpong Damai Tbk.',
  'KLBF' => 'Kalbe Farma Tbk.',
  'LPKR' => 'Lippo Karawaci Tbk.',
  'LPPF' => 'Lippo Karawaci Tbk.',
  'LSIP' => 'Indo Tambangraya Megah Tbk.',
  'MAPI' => 'Mitra Adiperkasa Tbk.',
  'MBKA' => 'Mitra Adiperkasa Tbk.',
  'MEDC' => 'Medco Energi Internasional Tbk.',
  'MIKA' => 'Mitra Keluarga Karyasehat Tbk.',
  'MNCN' => 'Media Nusantara Citra Tbk.',
  'MTEL' => 'Dayamitra Telekomunikasi Tbk.',
  'MTLA' => 'Dayamitra Telekomunikasi Tbk.',
  'MYOR' => 'Mayora Indah Tbk.',
  'PANI' => 'Pantai Indah Kapuk Dua Tbk.',
  'PGAS' => 'Perusahaan Gas Negara Tbk.',
  'PGEO' => 'Pertamina Geothermal Energy Tbk.',
  'PTBA' => 'Bukit Asam Tbk.',
  'PTPP' => 'Bukit Asam Tbk.',
  'PWON' => 'Pakuwon Jati Tbk.',
  'SIDO' => 'Industri Jamu dan Farmasi Sido Muncul Tbk.',
  'SILO' => 'Siloam International Hospitals Tbk.',
  'SMGR' => 'Semen Indonesia (Persero) Tbk.',
  'SMRA' => 'Summarecon Agung Tbk.',
  'SRTG' => 'Saratoga Investama Sedaya Tbk.',
  'TPIA' => 'Saratoga Investama Sedaya Tbk.',
  'TBIG' => 'Telkom Indonesia (Persero) Tbk.',
  'TINS' => 'Timah Tbk.',
  'TKIM' => 'Pabrik Kertas Tjiwi Kimia Tbk.',
  'TLKM' => 'Telkom Indonesia (Persero) Tbk.',
  'TOWR' => 'Tower Bersama Infrastructure Tbk.',
  'UNTR' => 'United Tractors Tbk.',
  'UNVR' => 'Unilever Indonesia Tbk.',
  'WIKA' => 'Wijaya Karya (Persero) Tbk.',
  'WSKT' => 'Waskita Karya (Persero) Tbk.',
  
  // Saham-saham dengan harga < 1000, FCA, dsb
  'BUMI' => 'Bumi Resources Tbk.',
  'BRMS' => 'Bumi Resources Minerals Tbk.',
  'ZATA' => 'Berani Rekreasi Perkasa Tbk.',
  'GOTO' => 'GoTo Gojek Tokopedia Tbk.',
  'CARE' => 'Metro Healthcare Indonesia Tbk.',
  'KPIG' => 'Bumi Resources Minerals Tbk.',
  'WIFI' => 'WiFi Indonesia Tbk.',
  'VKTR' => 'Ventura Investama Tbk.',
  'DEWA' => 'Darma Henwa Tbk.',
  'ENRG' => 'Energi Mega Persada Tbk.',
  'BIPI' => 'Bumi Resources Minerals Tbk.',
  'NANO' => 'Nusa Raya Cipta Tbk.',
  'CPRO' => 'Central Proteina Prima Tbk.',
  'SRIL' => 'Sri Rejeki Isman Tbk.',
  'TRAM' => 'Trada Alam Minera Tbk.',
  'MYRX' => 'Hanson International Tbk.',
  'IATA' => 'Infrastruktur Bisnis Sejahtera Tbk.',
  'KREN' => 'Hanson International Tbk.',
  'POLA' => 'Pollux Investasi Internasional Tbk.',
  'RIMO' => 'Rimo International Lestari Tbk.',
  'SIMA' => 'Siwani Makmur Tbk.',
  'SUGI' => 'Sugih Energy Tbk.',
  'BTEL' => 'Benakat Integra Tbk.',
  'AISA' => 'Indonesia Transport & Infrastructure Tbk.',
  'LCGP' => 'Langgeng Makmur Industri Tbk.',
  
  // Tambahan Saham < 1000 & FCA sesuai permintaan
  'BNBR' => 'Bakrie & Brothers Tbk.',
  'WMUU' => 'Widodo Makmur Unggas Tbk.',
  'JGLE' => 'Jaya Agra Wattie Tbk.',
  
  // Beberapa saham layer 3 / gocap lainnya yang sering dicari
  'STRK' => 'Lovina Beach Resort Tbk.',
  'BSBK' => 'Wira Global Solusi Tbk.',
  'GIAA' => 'Garuda Indonesia (Persero) Tbk.',
  'KAEF' => 'Garuda Indonesia (Persero) Tbk.',
  'FREN' => 'Smartfren Telecom Tbk.',
  'NINE' => 'Nusantara Infrastructure Tbk.',
  'ELIT' => 'Data Sinergitama Jaya Tbk.',
  'AWAN' => 'Era Digital Media Tbk.'
];

$count = 0;
$stmt = $mysqli->prepare("INSERT INTO stocks (symbol, name) VALUES (?, ?) ON DUPLICATE KEY UPDATE name=VALUES(name)");
foreach ($stocks as $sym => $name) {
    if (!$stmt) {
        die("Prepare failed: " . $mysqli->error);
    }
    // Finnhub expects standard symbols if possible or `.JK` for Yahoo. Let's insert exactly as is and let the api calls handle it. But wait, `index.php` loads symbol from this DB. If we use Yahoo it needs `.JK`, if Finnhub they still use normal ticker without .JK? Finnhub doesn't support IDX unless we use Yahoo. Let's add .JK
    $idx_sym = $sym . ".JK";
    $stmt->bind_param('ss', $idx_sym, $name);
    if($stmt->execute()) {
        $count++;
    }
}

echo "Berhasil memasukkan $count Data Saham Top BEI/IDX!\n";
?>